\newpage

# Introduction {-}
<!-- remarque générale : très intéressant, mais je pense que le DT est un peu éthéré, avec une longue partie théorique (qui pourrait être un peu réorganisée), et des applications pratiques qui viennent tard et qui ne collent finalement pas totalement aux textes. Et c'est bizarre de ne pas mettre du tout de séries réelles sur un DT sur les séries temporelles. Je proposerai de mettre un premier exemple avec des séries réelles (j'aurai préféré des séries françaises, mais ok pour les séries US en justifiant un peu - "à titre d'illustration, on utilise des séries qui ont l'avantage d'être stables..." ou qqch comme ça. Je laisserai les séries simulées pour la fin - on peut effectivement trouver que c'est intéressant en comparatifs - sachant qu'on rate une question, qui est de savoir si le processus sous-jacent est bien adapté au processus actuel-->
L’analyse du cycle économique, et en particulier la détection rapide des points de retournement d'une série, est un sujet de première importance dans l'analyse de la conjoncture économique. 
Pour cela, les indicateurs économiques sont généralement corrigés des variations saisonnières.
Toutefois, afin d'améliorer leur lisibilité, il peut être nécessaire d'effectuer un lissage supplémentaire afin de réduire le bruit, et ainsi analyser la composante tendance-cycle.
Par construction, les méthodes d’extraction de tendance-cycle sont étroitement liées aux méthodes de désaisonnalisation puisqu’elles sont généralement appliquées sur des séries corrigées des variations saisonnières. 

Les moyennes mobiles, ou les filtres linéaires, sont omniprésents dans les méthodes d'extraction du cycle économique et d'ajustement saisonnier^[
Une moyenne mobile est une méthode statistique qui consiste à appliquer une moyenne pondérée glissante à une série temporelle : à chaque date $t$ on calcule une moyenne pondérée de $p$ points passés et $q$ points futurs où $p,q\geq0$ dépend de la moyenne mobile.
]. 
Ainsi, la méthode de désaisonnalisation X-13ARIMA-SEATS utilise des moyennes mobiles de Henderson et des moyennes mobiles composites pour estimer les principales composantes d'une série chronologique. 
Au centre de la série, des filtres symétriques sont appliqués. 
 
En revanche, pour les estimations en temps réel, en raison de l’absence d’observations futures, toutes ces méthodes doivent s'appuyer sur des filtres asymétriques pour estimer les points les plus récents. 
Par exemple, même si X-13ARIMA-SEATS applique des moyennes symétriques aux prévisions obtenues à partir d'un modèle ARIMA, cela revient à appliquer des filtres asymétriques en fin de série, car les valeurs prédites sont des combinaisons linéaires de valeurs passées. 

<!-- une référence pour la 2e partie de la phrase? -->
<!-- Rep AQLT : pas de référence particulière, c'est une propriété statistique non étudiée en général -->
Si ces moyennes mobiles asymétriques ont de bonnes propriétés concernant la taille des révisions futures induites par le processus de lissage^[Voir par exemple @pierce1980SA.], elles induisent également, par construction, des déphasages qui retardent en général la détection en temps réel des points de retournement.

L'objectif de cette étude est de décrire et de comparer les approches récentes permettant l’extraction de tendance-cycle : <--! sauf erreur de ma part, ce n'est pas le même ordre que la présentation effective des modèles. Cela serait sans doute plus clair pourtant--> filtres polynomiaux locaux, méthodes fondées sur une optimisation des propriétés des filtres --- *Fidelity-Smoothness-Timeliness* (FST) et *accuracy, timeliness, smoothness* (ATS) ---, et filtres fondés sur les espaces de Hilbert à noyau reproduisant (RKHS).  
Bien que ces méthodes aient été présentées avec des approches générales de construction des filtres linéaires, leurs propriétés théoriques et leurs performances empiriques n'ont pas été comparées.
Cette étude décrit l'ensemble de ces méthodes en développant une formulation générale pour la construction des filtres, permettant de mettre en exergue les spécificités de chacune.\
Ainsi, les méthodes polynomiales ont l'avantage d'être simples et facilement compréhensibles, mais l'inconvénient est que le déphasage ne peut pas être contrôlé (ce qui peut introduire des délais plus importants dans la détection des points de retournement).
Les méthodes polynomiales peuvent également prendre en compte des problèmes complexes (comme l'autocorrélation induite par l'utilisation d'un plan de sondage rotatif avec une période de recouvrement).
Cette analyse montre aussi comment les filtres polynomiaux peuvent être étendus en ajoutant un critère permettant de contrôler le déphasage ou en les paramétrisant localement.\
Les RKHS permettent de construire facilement des filtres adaptés à toutes les fréquences (y compris des fréquences irrégulières) mais ont notamment l'inconvénient d'être numériquement instables (des problèmes d'optimisation peuvent apparaître, comme dans la méthode FST).\
La méthode FST a l'avantage d'être analytiquement soluble mais a l'inconvénient d'être plus difficilement paramétrisable car les différents critères utilisés ne sont pas normalisés : les poids associés aux différents critères n'ont donc pas de sens.

Toutes ces méthodes sont également comparées empiriquement sur des séries simulées et sur des séries réelles.
Cette analyse permet tout d'abord de montrer comment les problèmes d'optimisation des filtres issus des RKHS peuvent conduire à des filtres sous-optimaux (augmentation des révisions et du délai dans la détection des points de retournement).
Ensuite, la méthode proposée pour paramétrer localement les filtres polynomiaux permet à la fois de détecter plus rapidement les points de retournement et de réduire les révisions dans les estimations successives de la tendance-cycle.
Enfin, les résultats montrent que les futures études sur les méthodes d'estimations de la tendance-cycle peuvent probablement se restreindre à celles qui modélisent des tendances locales de degré au plus 2 : modéliser des tendances plus complexes aboutit à plus de révisions sans gain en termes de détection des points de retournement.

Cette étude est reproductible.
En particulier, toutes les méthodes décrites sont implémentées dans le *package* `r fa_r_project` `rjd3filters`^[https://github.com/palatej/rjd3filters.] et tous les codes utilisés sont disponibles sous https://github.com/InseeFrLab/XXXXXXXXX.

    
\newpage
