# De la désaisonnalisation à l'estimation tendance-cycle {#sec-SAtoTCE}
 
La plupart des indicateurs macroéconomiques (PIB, production, consommation, etc.) sont affectés par des effets saisonniers et des effets jours ouvrables qui perturbent l'analyse des évolutions infra-annuelles et les comparaisons spatiales.
C'est pourquoi les séries chronologiques sont généralement corrigées des variations saisonnières et des jours ouvrables, la *désaisonnalisation* étant le processus consistant à supprimer leurs effets.
 
Pour effectuer la désaisonnalisation, les méthodes de désaisonnalisation les plus populaires sont TRAMO-SEATS, une méthode paramétrique basée sur les modèles ARIMA (voir par exemple @maravall2004program), et X-13ARIMA-SEATS, une méthode non-paramétrique basée sur les moyennes mobiles (voir par exemple @ladiray2011seasonal).
Ces méthodes supposent que toute série temporelle $X_t$ peut se décomposer en quatre composantes :
 
1. Une composante saisonnière $S_t$.
 
2. Une composante jours ouvrables $D_t$.
 
3. Une composante tendance-cycle $TC_t$ qui contient la tendance (qui représente les évolutions de long terme) et le cycle (qui représente les évolutions cycliques autour de la tendance).
Dans ce cas, la tendance et le cycle sont estimés conjointement : les deux composantes peuvent en effet être difficiles à séparer (comment différentier les cycles courts des cycles longs ?) et les méthodes étudiées sont souvent appliquées sur des courtes (les cycles longs sont alors difficilement estimables).
 
4. Une composante irrégulière $I_t$ qui contient toutes les autres fluctuations.
 
Toutes ces composantes étant inobservées, l'estimation de l'une dépend de l'estimation des autres.
Ainsi, même si dans ce rapport, nous nous intéresserons aux méthodes d'extraction de tendance-cycle, celles-ci ne peuvent s'étudier indépendamment du processus du désaisonnalisation.
Ce lien explique également que toutes les méthodes utilisées dans ce rapport sont implémentées dans les bibliothèques de Java de JDemetra+^[Voir https://github.com/jdemetra/jdemetra-core.], le logiciel de désaisonnalisation recommandé par Eurostat.
Une interface `r fa_r_project` à l'ensemble des a été développée autour des méthodes présentées dans cette étude, grâce au *package* `rjd3filters`^[Disponible sur https://github.com/palatej/rjd3filters.].
 
Les filtres linéaires (ou moyennes mobiles) sont omniprésents dans la désaisonnalisation et l'estimation des différentes composantes.
Au centre de la série, des filtres dits symétriques sont appliqués (pour estimer une composante à la date $t$, on utilise autant de points après $t$ qu'avant $t$).
Pour extraire la tendance-cycle, le filtre symétrique le plus connu est celui de @henderson1916note, notamment utilisé dans l'algorithme X-13ARIMA.
Cependant, en raison du manque d’observations futures, les estimations en temps réel doivent s’appuyer sur des moyennes mobiles asymétriques.
Les moyennes mobiles asymétriques classiques minimisent les erreurs de révision mais introduisent des retards dans la détection des points de retournement (appelé déphasage, voir section \@ref(sec-propMM)).

Dans la littérature, différentes approches ont été envisagées pour l'extraction de tendance-cycle en temps réel^[Voir par exemple @alexandrov2012TEreview pour une revue de la littérature sur les méthodes d'extraction de tendance.].
Parmi les plus récentes, on peut citer :
 
- Les *Model-Based Approach*  --- approches basées sur les modèles --- supposent la spécification d'un modèle stochastique pour la tendance (modèle ARIMA, modèle d'espace d'état, etc.) et les estimations sont obtenues en minimisant une fonction de pénalité, généralement l'erreur quadratique moyenne.
C'est par exemple le cas du filtre de Kalman, du filtre de Wiener-Kolmogorov (utilisé dans TRAMO-SEATS) et de l'Approche par Filtre Direct de @trilemmaWMR2019 (section \@ref(sec-WildiMcLeroy)).
 
- Les méthodes d'extraction non paramétriques ne supposent pas que la structure d'un modèle est fixe et peuvent être facilement appliquées à n'importe quelle série temporelle.
C'est par exemple le cas des filtres d'Henderson et de @musgrave1964set (utilisés dans X-13ARIMA).
Les méthodes classiques peuvent être vues comme des régressions polynomiales locales, approche généralisée par @proietti2008 (section \@ref(sec-proietti)).
Les estimateurs non paramétriques peuvent également être reproduits en exploitant la méthodologie de l'espace de Hilbert du noyau reproducteur (RKHS), comme cela est fait par
@dagumbianconcini2008 (section \@ref(sec-rkhs)).

Bien que ces auteurs aient proposé des approches générales pour construire des filtres linéaires, ils ne font référence qu'aux méthodes les plus classiques (Henderson, Musgrave, Hodrick-Prescott, etc.) sans faire le lien avec les autres méthodes récentes.
Dans cette étude, nous proposons une approche unificatrice générale qui permettrait de reproduire l'ensemble de ces méthodes.
Cela a un double intérêt.
D'une part, cela permet de faire une première revue de la littérature sur les méthodes de construction des filtres linéaires pour l'analyse conjoncturelle.
D'autre part, cela permet de montrer les liens entre toutes ces approches et de les comparer en utilisant une même méthodologie.
 
Pour cela nous utiliserons l'approche générale de @ch15HBSA (section \@ref(subsec-formulegen)) qui ont également proposé une procédure globale pour construire des moyennes mobiles asymétriques permettant de minimiser les effets de déphasage (section \@ref(subsec-GuggemosEtAl)).
Des diagrammes synthétiques des liens entre les différentes méthodes étudiées sont présentés dans l'annexe \@ref(an-diag).
 
Nous nous intéresserons uniquement aux estimations intermédiaires de la tendance-cycle faites en temps réels.
Le filtre symétrique utilisé pour les estimations finales ne sera pas remis en cause et sera celui d'Henderson.
Nous nous concentrons également sur les méthodes qui pourraient être implémentées dans X-13ARIMA et qui pourra.
Pour maintenir la cohérence avec l'approche non paramétrique de X-13ARIMA, nous nous concentrons sur les méthodes d'extraction non paramétriques.
C'est pourquoi ni les filtres de l'approche de @trilemmaWMR2019 (section \@ref(sec-WildiMcLeroy)), ni d'autres approches basées sur des modèles ne sont, pour l'instant, utilisées dans les simulations.
Même si les différentes méthodes sont comparées en les appliquant sur des séries déjà désaisonnalisée, elles peuvent être intégrées dans l'algorithme de désaisonnalisation X-11 grâce à la fonction `rjd3filters::x11()`.
L'ensemble des filtres utilisés sont résumés dans l'annexe \@ref(an-graphs).
 

