--- 
title: "Estimation en temps réel de la tendance-cycle : apport de l’utilisation des filtres asymétriques dans la détection des points de retournement"
author: "Alain Quartier-la-Tente"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: article
link-citations: yes
description: "DT XXX"
themeoptions: "coding=utf8,language=french"
classoption: 'a4paper,french'
lang: "fr"
fontsize: 12pt
bibliography: [biblio.bib]
biblio-style: authoryear
babel-lang: french
urlcolor: blue
geometry: hmargin = 25mm, vmargin = 25mm
always_allow_html: true
---

```{r, eval = FALSE}
local({
    hook_plot <- knitr::knit_hooks$get('plot')
    knitr::knit_hooks$set(plot = function(x, options) {
        if(is.null(options$fig.cap) & is.null(options$fig.source))
            return(hook_plot(x, options))
        if(is_latex){
            res <-  knitr:::hook_plot_tex(x, options)
            # res <- add_footnote_latex(res, options)
        }else if(is_html){
            res <- hook_plot(x, options)
            # res <- add_footnote_html(res, options)
        }else{
            res <-  hook_plot(x, options)
        }
        res <- add_footnote(res, options)
        res
    })
})
```

```{r child = 'abstract/abstract.rmd', eval = !is_latex}
```

```{r,eval=is_latex, include = FALSE, cache = FALSE}
rmarkdown::render(input = 'abstract/abstract.rmd',
                  rmarkdown::latex_fragment(citation_package ="biblatex"),
                  quiet = TRUE)
# rmarkdown::render(input = 'abstract/abstract.rmd',
#                   bookdown::markdown_document2(bibliography = "biblio.bib"),
#                   params = list(bibliography = "biblio.bib"),
#                   quiet = TRUE)
# 
# rmarkdown::pandoc_convert('abstract.md',
#                           to = 'latex',from = "markdown",
#                           out = "abstract.tex",
#                           citeproc = FALSE,
#                           options = c("--bibliography=biblio.bib",
#                                       "--biblatex"
#                           ),
#                           wd ="abstract")
# rmarkdown::pandoc_convert(infile,
#                                   to = to,
#                                   from = "markdown",
#                                   citeproc = FALSE,
#                                   options = c("--bibliography=biblio.bib",
#                                               "--biblatex"
#                                               ),
#                                   output = outfile,
#                                   wd = dir)
```