--- 
always_allow_html: true
bibliography: "biblio.bib"
---

```{r, include=FALSE}
is_html <- knitr::is_html_output()
is_latex <- knitr::is_latex_output()


# Fontawesome
htmltools::tagList(rmarkdown::html_dependency_font_awesome())

if(is_html){
    fa_arrow_circle_right <- '<i class="fas fa-arrow-circle-right"></i>'
    fa_r_project <- '<i class="fab fa-r-project"></i>'
}else {
    if(is_latex){
        fa_arrow_circle_right <- "\\faIcon{arrow-circle-right}"
        fa_r_project <- "\\faIcon{r-project}"
    }else {
        fa_arrow_circle_right <- "->"
        fa_r_project <- 'R'
    }
}

```

\thispagestyle{fancy}

# Résumé {-}


:::: {.abstract}
`r if (is_html) '
:::{.title}
Résumé
:::
'`
L'analyse des cycles économiques, et en particulier la détection précoce des points de retournement, est un sujet majeur dans l'analyse de la conjoncture.
Les moyennes mobiles, ou les filtres linéaires, sont omniprésents dans les méthodes d'extraction de la tendance-cycle et d’ajustement saisonnier.
Au centre de la série,  des moyennes mobiles symétriques sont appliquées^[
C’est-à-dire que pour estimer la tendance-cycle à la date $t$,  on utilise autant de points dans le passé que dans le futur et le même poids est associé aux observations passées et futures.
].
Cependant, en raison du manque d'observations futures, les estimations en temps réel doivent s'appuyer sur des moyennes mobiles asymétriques.
C’est ce qui est par exemple fait dans les méthodes de désaisonnalisation les plus utilisées, X-13ARIMA, qui prolonge la série sur 1 an par un modèle ARIMA.
Les prévisions étant des combinaisons linéaires du passé,  cela revient en réalité à utiliser des moyennes mobiles asymétriques dont les coefficients sont optimisés par rapport à la prévision avec une longueur d’avance.

La construction de moyennes mobiles asymétriques performantes en termes de fidélité (préservation du signal), de révision, de lissage et de déphasage (délais dans la détection de points de retournement) est un sujet de recherche toujours ouvert.
Cette étude décrit et compare des approches récentes pour la construction de moyennes mobiles asymétriques, utilisées pour l’estimation en temps réel de la tendance-cycle : filtres polynomiaux locaux [@proietti2008; @GrayThomson1996] ; méthodes basées sur une optimisation sous contrainte d’une somme pondérée de critères de qualité des moyennes mobiles [@ch15HBSA; @trilemmaWMR2019] ; et filtres basés sur les espaces de Hilbert à noyau reproduisant (RKHS) @dagumbianconcini2008.
Elle montre également comment les filtres polynomiaux locaux peuvent être étendus pour inclure un critère de temporalité afin de minimiser le déphasage.
Enfin,  cette étude montre qu'il est possible d'établir une approche unificatrice générale qui permet de reproduire l’ensemble des méthodes étudiées.

La comparaison des méthodes sur séries simulées montre qu'il est important d'adapter la longueur du filtre à la variabilité de la série. 
Même si certains filtres RKHS pourraient donner des résultats satisfaisant en termes de délais dans la détection des points de retournement, leur utilisation doit être limitées aux premières estimations de la tendances-cycles. Lorsque l'on se rapproche de l'estimation finale (i.e., lorsque beaucoup de points dans le futur sont connus), d'autres méthodes devraient être utilisées afin de limiter les révisions. Les filtres RKHS sont par ailleurs sujets à problèmes d'optimisation.
Enfin, lorsque la longueur du filtre est adapté à la variabilité de la série, chercher à conserver des tendances polynomiales de degré supérieur à un semble introduire de la variance dans les estimations (et donc plus de révisions) sans gain significatif en termes de détection de point de retournement.

Cette étude est reproductible. En particulier, toutes les méthodes décrites sont implémentées dans le *package* `r fa_r_project` `rjd3filters` (https://github.com/palatej/rjd3filters) et tous les codes utilisées sont disponibles sous https://github.com/InseeFrLab/XXXXXXXXX.
::::


# Abstract {-}

:::: {.abstract}
`r if (is_html) '
:::{.title}
Abstract
:::
'`
This paper describes and compares different approaches to build asymmetric filters: local polynomials filters, methods based on an optimization of filters' properties (Fidelity-Smoothness-Timeliness, FST, approach and a data-dependent filter) and filters based on Reproducing Kernel Hilbert Space.
It also describes how local polynomials filters can be extended to include a timeliness criterion to minimize phase shift.
All these methods can be seen as a special case of a general unifying framework to derive linear filters.

This paper shows that, when the length of the filter is adapted to the variability of the series, constraining asymmetric filters to preserve constant trends (and not necessarily polynomial ones) reduce revision error and time lag. 
Therefore, future studies on the subject can focus on these filters.
Moreover, with RKHS filters some optimisation issues can occurs and they might lead to erratic estimation.
They might be able to produce satisfying results in terms of phase-shift and revisions, but they should be avoid for the last estimates of the trend-cycle component: other methods should then be prefered to reduce revisions with the final estimates.

All the methods are implemented in the `r fa_r_project` package `rjd3filters` and the results can be easily reproduced.
The programs used, and a web version of this report, are available at https://github.com/InseeFrLab/XXXXXXXXX.
::::

